[package]
name = "cw_grid_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
env_logger = "0.11.1"
log = "0.4.20"
tera = "1.19.1"
