version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PUZZLE_PATH: /puzzles
      PUZZLE_PORT: 5051
      PUZZLE_THREADS: 64
      RUST_LOG: warn
    volumes:
      - puzzle_data:/puzzles
    ports:
      - "5051:5051"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  
  stage_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PUZZLE_PATH: /puzzles
      PUZZLE_PORT: 5052
      PUZZLE_THREADS: 64
      RUST_LOG: info 
    volumes:
      - stage_puzzle_data:/puzzles
    ports:
      - "5052:5052"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  puzzle_data:
  stage_puzzle_data:
