name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag jhb123/cw-live-edit:latest
    
      - name: Push to Docker Hub
        run: docker push docker.io/jhb123/cw-live-edit:latest

      - name: Login to AWS
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_REPO }}

      - name: Push to AWS ECR
        run: |
          docker image tag jhb123/cw-live-edit:latest ${{ secrets.AWS_REPO }}/cw-live-edit:latest
          docker push ${{ secrets.AWS_REPO }}/cw-live-edit:latest
